-- Versioned, monotonic UI event projection for reconnect replay.

ALTER TABLE run_events
    ADD COLUMN IF NOT EXISTS sequence BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS projection_version SMALLINT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS thread_id TEXT,
    ADD COLUMN IF NOT EXISTS turn_id TEXT,
    ADD COLUMN IF NOT EXISTS item_id TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_run_events_sequence
    ON run_events(sequence);
CREATE INDEX IF NOT EXISTS idx_run_events_run_sequence
    ON run_events(run_id, sequence);
CREATE INDEX IF NOT EXISTS idx_run_events_thread_item
    ON run_events(thread_id, turn_id, item_id)
    WHERE item_id IS NOT NULL;
