use sqlx::postgres::PgConnection;
use sqlx::{AssertSqlSafe, Connection, Executor};
use uuid::Uuid;

const REMOVE_PROVIDER_DEFINITION_OWNER: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../migrations/20260824000070_remove_provider_definition_owner.sql"
));

/// The strict migration is only safe on development databases that have been
/// rebuilt without the retired Platform Provider-definition mirror.
#[tokio::test]
#[ignore = "requires TEST_DATABASE_URL pointing at a disposable PostgreSQL database"]
async fn removes_only_an_empty_retired_provider_definition_table() {
    let database_url = std::env::var("TEST_DATABASE_URL").expect("TEST_DATABASE_URL");
    let schema = format!("provider_definition_migration_{}", Uuid::now_v7().simple());
    let mut connection = PgConnection::connect(&database_url)
        .await
        .expect("connect disposable PostgreSQL database");

    // `schema` contains only a UUID generated by this test, not caller input.
    sqlx::query(AssertSqlSafe(format!("CREATE SCHEMA {schema}")))
        .execute(&mut connection)
        .await
        .expect("create isolated migration schema");
    sqlx::query(AssertSqlSafe(format!("SET search_path TO {schema}")))
        .execute(&mut connection)
        .await
        .expect("select isolated migration schema");

    sqlx::query("CREATE TABLE profile_provider_definitions (provider_id text NOT NULL)")
        .execute(&mut connection)
        .await
        .expect("create empty retired table");
    connection
        .execute(REMOVE_PROVIDER_DEFINITION_OWNER)
        .await
        .expect("drop empty retired table");
    let removed: Option<String> =
        sqlx::query_scalar("SELECT to_regclass('profile_provider_definitions')")
            .fetch_one(&mut connection)
            .await
            .expect("check removed table");
    assert_eq!(removed, None);

    sqlx::query("CREATE TABLE profile_provider_definitions (provider_id text NOT NULL)")
        .execute(&mut connection)
        .await
        .expect("recreate retired table");
    sqlx::query("INSERT INTO profile_provider_definitions (provider_id) VALUES ('legacy')")
        .execute(&mut connection)
        .await
        .expect("insert legacy Provider definition");
    let error = connection
        .execute(REMOVE_PROVIDER_DEFINITION_OWNER)
        .await
        .expect_err("non-empty retired table must require a development rebuild");
    assert!(error
        .to_string()
        .contains("profile_provider_definitions contains legacy Provider state"));
    let retained: Option<String> =
        sqlx::query_scalar("SELECT to_regclass('profile_provider_definitions')")
            .fetch_one(&mut connection)
            .await
            .expect("check retained table after rejection");
    assert_eq!(retained.as_deref(), Some("profile_provider_definitions"));

    sqlx::query("SET search_path TO public")
        .execute(&mut connection)
        .await
        .expect("restore search path");
    sqlx::query(AssertSqlSafe(format!("DROP SCHEMA {schema} CASCADE")))
        .execute(&mut connection)
        .await
        .expect("remove isolated migration schema");
}
