use sqlx::postgres::PgConnection;
use sqlx::{AssertSqlSafe, Connection, Executor};
use uuid::Uuid;

const REMOVE_TASK_MODEL_SELECTION: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../migrations/20260824000071_remove_task_model_selection.sql"
));

async fn create_isolated_schema(connection: &mut PgConnection, schema: &str) {
    // `schema` contains only a UUID generated by this test, not caller input.
    sqlx::query(AssertSqlSafe(format!("CREATE SCHEMA {schema}")))
        .execute(&mut *connection)
        .await
        .expect("create isolated migration schema");
    sqlx::query(AssertSqlSafe(format!("SET search_path TO {schema}")))
        .execute(&mut *connection)
        .await
        .expect("select isolated migration schema");
    sqlx::query("CREATE TABLE tasks (model_provider text, model text)")
        .execute(&mut *connection)
        .await
        .expect("create legacy tasks table");
    sqlx::query(
        "ALTER TABLE tasks ADD CONSTRAINT tasks_model_selection_pair_check CHECK (\
         (model_provider IS NULL AND model IS NULL) OR \
         (model_provider IS NOT NULL AND model IS NOT NULL))",
    )
    .execute(&mut *connection)
    .await
    .expect("create legacy pair constraint");
    sqlx::query(
        "CREATE TABLE platform_configuration (scope_kind text, scope_id text, config_key text)",
    )
    .execute(&mut *connection)
    .await
    .expect("create configuration table");
}

async fn drop_isolated_schema(connection: &mut PgConnection, schema: &str) {
    sqlx::query("SET search_path TO public")
        .execute(&mut *connection)
        .await
        .expect("restore search path");
    sqlx::query(AssertSqlSafe(format!("DROP SCHEMA {schema} CASCADE")))
        .execute(&mut *connection)
        .await
        .expect("remove isolated migration schema");
}

/// Migration 71 accepts only a development database that has already removed
/// every Task pair and the retired global selection key.
#[tokio::test]
#[ignore = "requires TEST_DATABASE_URL pointing at a disposable PostgreSQL database"]
async fn removes_only_empty_task_model_selection_state() {
    let database_url = std::env::var("TEST_DATABASE_URL").expect("TEST_DATABASE_URL");
    let mut connection = PgConnection::connect(&database_url)
        .await
        .expect("connect disposable PostgreSQL database");

    let empty_schema = format!("task_model_empty_{}", Uuid::now_v7().simple());
    create_isolated_schema(&mut connection, &empty_schema).await;
    connection
        .execute(REMOVE_TASK_MODEL_SELECTION)
        .await
        .expect("remove empty Task model selection state");
    let remaining_columns: i64 = sqlx::query_scalar(
        "SELECT count(*) FROM information_schema.columns \
         WHERE table_schema = current_schema() AND table_name = 'tasks' \
           AND column_name IN ('model_provider', 'model')",
    )
    .fetch_one(&mut connection)
    .await
    .expect("inspect removed Task columns");
    assert_eq!(remaining_columns, 0);
    drop_isolated_schema(&mut connection, &empty_schema).await;

    let task_schema = format!("task_model_pair_{}", Uuid::now_v7().simple());
    create_isolated_schema(&mut connection, &task_schema).await;
    sqlx::query("INSERT INTO tasks (model_provider, model) VALUES ('legacy', 'legacy-model')")
        .execute(&mut connection)
        .await
        .expect("insert legacy Task model pair");
    let error = connection
        .execute(REMOVE_TASK_MODEL_SELECTION)
        .await
        .expect_err("Task model pair must require a development rebuild");
    assert!(error
        .to_string()
        .contains("tasks contains legacy Provider/model state"));
    drop_isolated_schema(&mut connection, &task_schema).await;

    let global_schema = format!("task_model_global_{}", Uuid::now_v7().simple());
    create_isolated_schema(&mut connection, &global_schema).await;
    sqlx::query(
        "INSERT INTO platform_configuration (scope_kind, scope_id, config_key) \
         VALUES ('global', 'global', 'models.default_selection')",
    )
    .execute(&mut connection)
    .await
    .expect("insert retired global selection");
    let error = connection
        .execute(REMOVE_TASK_MODEL_SELECTION)
        .await
        .expect_err("global model selection must require a development rebuild");
    assert!(error
        .to_string()
        .contains("platform_configuration contains legacy models.default_selection"));
    drop_isolated_schema(&mut connection, &global_schema).await;
}
