// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityDeclaration } from "./CapabilityDeclaration";
import type { CompatibilityRange } from "./CompatibilityRange";
import type { ServerIdentity } from "./ServerIdentity";

/**
 * Top-level capability manifest returned during `initialize`.
 */
export type CapabilityManifest = { schemaVersion: string, generatedAt: string, server: ServerIdentity, compatibility: CompatibilityRange, capabilities: Array<CapabilityDeclaration>, };
