// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityStatus } from "./CapabilityStatus";
import type { MethodSet } from "./MethodSet";
import type { StructuredReason } from "./StructuredReason";
import type { JsonValue } from "./serde_json/JsonValue";

export type CapabilityDeclaration = { id: string, version: string, status: CapabilityStatus, methods: MethodSet, limits?: { [key in string]?: JsonValue } | null, reason?: StructuredReason | null, experimental?: boolean, };
