// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelProviderModelSummary = { modelId: string, modelName: string | null, maxTokenLen: bigint | null, maxOutputTokens: bigint | null, showInPicker: boolean, contextWindow: bigint | null, };
