// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelProviderSummary } from "./ModelProviderSummary";

export type ModelProviderListResponse = { data: Array<ModelProviderSummary>, currentProviderId: string,
/**
 * Exact model selected in the current Profile configuration; null when unset.
 */
currentModelId: string | null, };
