// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelProviderModelSummary } from "./ModelProviderModelSummary";
import type { ModelProviderModelsListFailure } from "./ModelProviderModelsListFailure";

export type ModelProviderModelsListResult = { "type": "success", models: Array<ModelProviderModelSummary>, } | { "type": "failure", error: ModelProviderModelsListFailure, };
