// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests a fresh model catalog from one configured Provider.
 *
 * The Provider is resolved by the Runtime from its current config registry;
 * callers never supply a URL or credentials.
 */
export type ModelProviderModelsListParams = { providerId: string, };
