// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelProviderKind } from "./ModelProviderKind";
import type { ModelProviderModelSummary } from "./ModelProviderModelSummary";

export type ModelProviderSummary = { id: string, name: string, baseUrl: string | null, envKey: string | null, wireApi: string, kind: ModelProviderKind, isCurrent: boolean, modelCount: number, canEdit: boolean, canDelete: boolean, canFetchModels: boolean, models: Array<ModelProviderModelSummary>, };
