// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects an explicit multi-agent engine for one new or forked thread.
 *
 * This request-only choice does not write Profile or Project configuration.
 */
export type ThreadMultiAgentBackend = "v1";
